[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CiliaSim"
description = "Edge-based force accumulation and Voronoi-driven tissue toy model"
version = "0.0.1"
readme = "README.md"
authors = [
    {name = "Guillaume Macneil", email = "gc@gmail.com"},
]
dependencies = [
    "tqdm",
    "numpy",
    "scipy",
    "matplotlib",
    "numba",
    "pytest",
    "ruff",
    "pre-commit"
]

[tool.ruff]
select = ["E", "F", "W", "C"]
ignore = ["E501"]
extend-include = ["*.ipynb"]

[tool.pytest.ini_options]
filterwarnings = "ignore"